# docker-compose.yml
version: "3"
services:
  app:
    build: .
    container_name: node-container
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "9229:9229"
    volumes:
      - ./:/app
  postgres:
    image: postgres:9.6.8-alpine
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: postgres